# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key => ENV['MAIL_API_KEY']
  config.secret_key => ENV['MAIL_SECRET_KEY']
  config.default_from = 'no-reply@catshop.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
config.api_key = 'f233c5a0ca56ed7c6b59617dce404b5c'
config.secret_key = 'fe174bf82b740ef25e9e57e1a663435d'